### ISSUE TITLE
InfiniteLoaderModule

### ISSUE THREAD

**Issue by nie55352177** [cipchk/ngx-weui#3]
InfiniteLoaderModule 在tabbar中不触发loadmore回调

**Comment by cipchk** [comment]
这是由于 `weui-infiniteloader` 标签在DOM中默认是 `dispaly:inline` 这样会导致无法获取到滚动高度，我会在下一个版本修复该问题。

当前可以在自行对标签增加 `display:block` 得以解决。

```css
weui-infiniteloader {
display: block;
}
```
